# Netlify configuration for HireMyCar Angular application
[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist/HireMycar/browser"

  ## Redirect for Single Page Applications like Angular.
  ## This is needed for Angular routing to work properly.
  [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

  ## Headers for better performance and security
  [[headers]]
    for = "/*"
    [headers.values]
      X-Frame-Options = "DENY"
      X-XSS-Protection = "1; mode=block"
      X-Content-Type-Options = "nosniff"
      Referrer-Policy = "strict-origin-when-cross-origin"

  ## Cache static assets
  [[headers]]
    for = "/assets/*"
    [headers.values]
      Cache-Control = "public, max-age=31536000, immutable"

  ## Cache favicon and manifest
  [[headers]]
    for = "/*.svg"
    [headers.values]
      Cache-Control = "public, max-age=86400"

  [[headers]]
    for = "/*.ico"
    [headers.values]
      Cache-Control = "public, max-age=86400"

  ## (optional) Settings for Netlify Dev
  ## https://github.com/netlify/cli/blob/main/docs/netlify-dev.md#project-detection
  #[dev]
  #  command = "yarn start" # Command to start your dev server
  #  port = 3000 # Port that the dev server will be listening on
  #  publish = "dist" # Folder with the static content for _redirect file

  ## more info on configuring this file: https://ntl.fyi/file-based-build-config
